### ISSUE TITLE
Docs for sending a template

### ISSUE THREAD

**Issue by leonardocustodio** [mailersend/mailersend-laravel-driver#54]
I see the `template_id` but what should I return in the `Content` for sending a template?

**Comment by fosron** [comment]
@leonardocustodio Just empty text, it will be ignored in the API.

**Comment by jphilung** [comment]
Laravel will throw an error if the parameters of `new Content` are empty. Use htmlString with dummy content instead of the view or text parameters, e.g.

```
return new Content(
  htmlString: "<div></div"
);
```

@fosron , the docs should be updated to reflect this. For the moment, it shows :

```
return new Content(
  view: "mail.example",
  text: "mail.example",
);
```

The view and text parameters expect a Laravel view and will throw an error is it empty or the view does not exist.
